### ISSUE TITLE
Bugs encountered during local runtime

### ISSUE THREAD

**Issue by ZhangCeGitHub** [Pamasi/sgg_av#5]
When attempting to run locally, I encountered the following issues:
1.The "generate_tg.sh" script is missing.
2.How to obtain the images corresponding to Traffic_Genome?

**Comment by Pamasi** [comment]
Hi,

Thank you for your interest in my research.

I've added the missing file. It will automatically download the traffic genome dataset from my  [Google Drive link](https://drive.google.com/file/d/1l1wL4kNMTOG3DYwW7GLms-C5mB6lu3E3/view?usp=drive_link).
To run the script you have to **unzip** and **curl** installed on your Linux machine, otherwise you can follow the instructions in the [Traffic Genome](https://github.com/Milomilo0320/Traffic-Scene-Graph-1000) repository.

Best regards, 
Paolo Dimasi

**Comment by ZhangCeGitHub** [comment]
Thank you so much for your assistance! The program is now running smoothly！
